export default function Home() {
  return <div style={{ padding: '2rem', background: '#000', color: '#0f0', fontFamily: 'monospace' }}>
    <h1>KLAW Demo</h1>
    <p>Next.js landing page generated by KLAW</p>
  </div>;
}