const ArchitectAgent = require('./architect');
const FileWriterAgent = require('./writer');
const ShellAgent = require('./shell');
const FixerAgent = require('./fixer');
const { appendMemory, appendMemoryBlock } = require('../memory');
const fs = require('fs');
const path = require('path');

function parseConfig() {
  const os = require('os');
const configPath = path.join(os.homedir(), '.klaw', 'config.json');
  if (fs.existsSync(configPath)) {
    return JSON.parse(fs.readFileSync(configPath, 'utf8'));
  }
  return {
    workspace: './klaw-workspace',
    providers: {},
    permissions: {
      allowFileWrite: true,
      allowShellCommands: false
    }
  };
}

async function executeTask(task) {
  const config = parseConfig();
  const workspace = config.workspace || './klaw-workspace';

  if (!fs.existsSync(workspace)) {
    fs.mkdirSync(workspace, { recursive: true });
    console.log(`[KLAW][SYSTEM] Workspace created: ${workspace}`);
  }

  appendMemory('task', `Received task: ${task}`);

  const architect = new ArchitectAgent(task);
  const steps = architect.analyze();
  architect.log(`Planning ${steps.length} steps`);

  const writer = new FileWriterAgent(workspace);
  const shell = new ShellAgent(config);
  const fixer = new FixerAgent();

  const context = {
    workspace: workspace,
    task: task,
    steps: steps,
    architect: architect,
    writer: writer,
    shell: shell,
    fixer: fixer,
    memory: { appendMemory, appendMemoryBlock }
  };

  try {
    await executeSteps(context, steps);
    console.log(`[KLAW][SYSTEM] Demo complete. Workspace: ${workspace}`);
    appendMemory('result', 'Demo completed');
  } catch (error) {
    console.log(`[KLAW][SYSTEM] Error: ${error.message}`);
    appendMemory('error', error.message);
    fixer.suggestFix(error);
  }
}

async function executeSteps(context, steps) {
  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    context.architect.log(`Executing step ${i + 1}/${steps.length}: ${step}`);

    if (step.includes('package.json')) {
      await createNextJsProject(context);
    } else if (step.includes('Install dependencies')) {
      await installDependencies(context);
    } else if (step.includes('Start development server')) {
      await startServer(context);
    }
  }
}

async function createNextJsProject(context) {
  const { workspace } = context;

  const packageJson = {
    name: 'klaw-demo',
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start'
    },
    dependencies: {
      next: '^14.0.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0'
    }
  };

  context.writer.write('package.json', JSON.stringify(packageJson, null, 2));
  context.writer.write('pages/index.js', `export default function Home() {
  return <div style={{ padding: '2rem', background: '#000', color: '#0f0', fontFamily: 'monospace' }}>
    <h1>KLAW Demo</h1>
    <p>Next.js landing page generated by KLAW</p>
  </div>;
}`);

  context.writer.write('next.config.js', `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;`);

  context.writer.write('styles/globals.css', `html, body { margin: 0; padding: 0; }
body { background: #000; color: #0f0; }`);

  appendMemory('files', 'Created package.json, pages/index.js, next.config.js, styles/globals.css');
}

async function installDependencies(context) {
  context.architect.log('Delegating to ShellAgent for npm install');
  const result = await context.shell.run('npm install', 'Install project dependencies');
  if (!result) {
    context.fixer.retry('npm install', 'Install failed');
    appendMemory('error', 'npm install failed');
  }
}

async function startServer(context) {
  context.architect.log('Delegating to ShellAgent for npm run dev');
  const result = await context.shell.run('npm run dev', 'Start development server');
  if (result) {
    appendMemory('success', 'Dev server started');
  } else {
    appendMemory('error', 'Dev server failed to start');
    context.fixer.retry('npm run dev', 'Server startup failed');
  }
}

module.exports = { executeTask };